scrape-endpoint:
   uri-path: "prometheus/scrape"
azure-authentication:
   application-id: "xyz"
   application-secret: "abc"
metrics:
- metric:
  name: "my-name"
  resource-type: "Microsoft.ServiceBus"
- metric:
  name: "my-name"
  resource-type: "Microsoft.WebApps"