FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine AS build
WORKDIR /src
ARG VERSION="UNSET-VERSION"
COPY src/Promitor.Core/* Promitor.Core/
COPY src/Promitor.Agents.Core/* Promitor.Agents.Core/
COPY src/Promitor.Core.Scraping/* Promitor.Core.Scraping/
COPY src/Promitor.Core.Contracts/* Promitor.Core.Contracts/
COPY src/Promitor.Core.Telemetry/* Promitor.Core.Telemetry/
COPY src/Promitor.Integrations.Azure/* Promitor.Integrations.Azure/
COPY src/Promitor.Integrations.AzureMonitor/* Promitor.Integrations.AzureMonitor/
COPY src/Promitor.Integrations.AzureStorage/* Promitor.Integrations.AzureStorage/
COPY src/Promitor.Integrations.Sinks.Statsd/* Promitor.Integrations.Sinks.Statsd/
COPY src/Promitor.Integrations.Sinks.Atlassian.Statuspage/* Promitor.Integrations.Sinks.Atlassian.Statuspage/
COPY src/Promitor.Integrations.Sinks.Prometheus/* Promitor.Integrations.Sinks.Prometheus/
COPY src/Promitor.Agents.Scraper/* Promitor.Agents.Scraper/
RUN dotnet publish Promitor.Agents.Scraper/Promitor.Agents.Scraper.csproj --configuration release --output app /p:Version=$VERSION

FROM mcr.microsoft.com/dotnet/aspnet:3.1-alpine AS runtime
WORKDIR /app
ENV PROMITOR_CONFIG_FOLDER="/config/"

COPY --from=build /src/app .

ENTRYPOINT ["dotnet", "Promitor.Agents.Scraper.dll"]

# docker build . --file ./Promitor.Agents.Scraper/Dockerfile.linux --tag promitor-agent-scraper --build-arg VERSION=2.4.1 --no-cache