FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
WORKDIR /src
COPY . .

RUN dotnet publish Promitor.Agents.ResourceDiscovery/Promitor.Agents.ResourceDiscovery.csproj --configuration release --output app

FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS runtime
WORKDIR /app
ENV PROMITOR_CONFIG_FOLDER="/config/"

COPY --from=build /src/app .

ENTRYPOINT ["dotnet", "Promitor.Agents.ResourceDiscovery.dll"]